config/routes.rb
# Encoding: utf-8
Rails.application.routes.draw do
  root to: 'static_pages#index'
  namespace :admin do
    resources :snippets, only: [:index, :edit, :update]
    root to: 'snippets#index'
  end
end

app/models/settings.rb
# Sets the username and password for the admin interface
class Settings

  def self.username
    config['username']
  end

  def self.password
    config['password']
  end

  def self.config
    @yaml ||= YAML.load_file("#{Rails.root}/config/application.yml")[Rails.env]
  end
end

app/models/snippet.rb
# Editable piece of text
class Snippet < ActiveRecord::Base
  validates :slug, {
    presence: true,
    uniqueness: true,
    length: { in: 4..32 }
  }
  validates :description, {
    presence: true,
    length: { in: 4..32 }
  }
  validates :content, {
    presence: true
  }
  # validates :html_cache, {
  #   presence: true
  # }

  # Returns the snippet content as HTML
  def to_html
    RedCloth.new(content).to_html
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/snippets_controller.rb
# Controller for editing snippets in the admin interface
class Admin::SnippetsController < Admin::BaseController
  helper_method :collection, :resource

  def index
  end

  def edit
  end

  def update
    if resource.update_attributes(snippet_params)
      redirect_to admin_snippets_url
    else
      render :edit
    end
  end

  protected

  def collection
    @snippets ||= Snippet.all
  end

  def resource
    @snippet ||= Snippet.find(params[:id])
  end

  private

  def snippet_params
    params.require(:snippet).permit(:content, :description)
  end
end

app/controllers/application_controller.rb
# Encoding: utf-8
#
# 99% of your controllers in your application should have this controller in its inheritance chain.
# So do things here like enforce security by default, always check for authroization and those
# types of things.
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate!

  protected

  def authenticate!
    authenticate_or_request_with_http_basic do |username, password|
      username == Settings.username && password == Settings.password
    end
  end
end

app/controllers/static_pages_controller.rb
# Encoding: utf-8
#
# There is nothing really special here. This is the most basic way of
# getting started with page rendering to replace the default Rails root
# page and start stubbing out an other pages for design purposes.
class StaticPagesController < ApplicationController
  skip_before_action :authenticate!, only: :index
  # The homepage
  def index
  end

end

app/helpers/application_helper.rb
# Encoding: utf-8
# These helpers get included in every view rendering that occures through any controller in the
# application so don't start jamming this full of methods that only once controller and action
# pair whould need.
module ApplicationHelper
end

app/views/admin/snippets/_snippet.html.haml
%tr[snippet]
  %td= snippet.slug
  %td= snippet.description
  %td
    = link_to 'edit', edit_admin_snippet_url(snippet)

app/views/admin/snippets/edit.html.haml
%h1 Edit Snippet
= simple_form_for resource, url: admin_snippet_path(resource) do |form|
  = form.input :description
  = form.input :content, input_html: { cols: 80, rows: 10 }
  = form.submit

app/views/admin/snippets/index.html.haml
%h1 Snippets
%table
  %thead
    %tr
      %th slug
      %th description
      %th actions
  %tbody
    = render collection

app/views/application/_countdown.html.haml
.counter-container
  .counter-box
    .countdown
      .counter-item.item-day 00
      .counter-item 00
      .counter-item 00
      .counter-item 00
  = Snippet.find_by_slug!('countdown').to_html.html_safe

app/views/application/_directions.html.haml
#directions
  .street-address{ data: { todo: 'Schema.org the address' } }
    Range Road 260 Township Road 492
  .map
    TODO: Google Maps JavaScript

app/views/application/_donations.html.haml
#donations
  = Snippet.find_by_slug!('donations').to_html.html_safe

app/views/application/_footer.html.haml
%footer

app/views/application/_header.html.haml
%header
  %nav.navbar.navbar{ role: :navigation }
    .container-fluid
      .navbar-header
        = link_to 'Leduc Country Lights', root_url, class: 'navbar-brand'
      .navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'Schedule',   root_url(anchor: :schedule)
          %li= link_to 'Dontations', root_url(anchor: :donations)
          %li= link_to 'Directions', root_url(anchor: :directions)
          %li= link_to 'Photos',     root_url(anchor: :directions)
          %li= link_to 'Volunteer',  root_url(anchor: :volunteer)

app/views/application/_image_gallery.html.haml
#photos
  = Snippet.find_by_slug!('gallery').to_html.html_safe

  %ul
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'
    %li= image_tag 'http://lorempixel.com/400/400/'

  .clear-fix

app/views/application/_schedule.html.haml
#schedule{ data: { todo: 'Schema.org the dates' } }
  Lights start/turn on November 28, 2014 - January 4, 2015
  Lights Open 7 Days A Week

  See Santa & Free Hot Chocolate - 5:00pm - 9:00pm 
  November 28, 29, 30
  December 5, 6, 7
  December 12, 13, 14
  December 19, 20, 21, 22

app/views/application/_volunteers.html.haml
#volunteers
  = Snippet.find_by_slug!('volunteers').to_html.html_safe

app/views/layouts/admin/base.html.haml
!!! 5
%html
  %head

    %title Leduc Country Lights Admin

  %body

    = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head

    %title Leduc Country Lights

    = stylesheet_link_tag 'country-lights'

  %body

    = render 'header'
    
    = yield

    = render 'footer'

app/views/static_pages/index.html.haml
= render 'countdown'
= render 'schedule'
= render 'donations'
= render 'directions'
= render 'image_gallery'
= render 'volunteers'